### ISSUE TITLE
EvaluationContext.Default issue

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#16]
When I define
`private readonly EvaluationContext evalContext = new EvaluationContext(EvaluationContext.Default);`
And set
`evalContext.SetIgnoreCase(true);`
I can't use `PI` and `E`

But when I define
`private readonly EvaluationContext evalContext = new EvaluationContext();`
`evalContext.LoadAllPackages();`
And set
`evalContext.SetIgnoreCase(true);`
I can use `PI` and `E`

**Comment by mastersign** [comment]
This is intended behavior. When you call `SetIgnoreCase(true)` on `evalContext`, the lookup settings of this instance are changed. But you did not change the lookup settings of the instance referenced by `EvalationContext.Default`.

In summary, when you chain evaluation contexts by passing one to the `EvaluationContext` constructor in order to create another – every instance in the chain keeps its own lookup settings (ignore case properties). I designed it that way, to leave more flexibilty in the configuration of the evaluation context.

**Comment by kaifuzi** [comment]
I'm clear now, thanks!
