### ISSUE TITLE
Add function left and right

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#19]
Could you please add function `left` and `right` for string?
I understand that Mastersign.Expressions already has function `substr`, but `left` and `right` are easier  for user to extract string from left or right, especially for `right`.

**Comment by mastersign** [comment]
Do the functions need to be called `left` and `right`? Because there are some languages (like hebrew, e.g.) wich are written right to left, and the terms would lie about thier function. That is the reason, why string related methods in the .NET world use the terms _start_ and _end_ (e. g. `TrimStart()`, `TrimEnd()`). I guess for some people `right` and `left` might be more intuitive, for others it is just the opposite.

The terms _head_ and _tail_ may come to mind, but these have a specific meaning in the functional programming tradition: _head_ meaning the first item of a sequence and _tail_ meaning all items but the first of a sequence.

**Comment by kaifuzi** [comment]
@mastersign You are right, some languages which are written right to left. But for `left` and `right` themselves, I think they have absolute meaning, the best example is left hand and right hand.
The reason I want to add function `left` and `right`, it's because I take the concept from excel(as your introduction: a small EXCEL like expression language), and I think it's easy for user to extract string from start or end.
If you have better function name for this, then plase add them to Mastersign.Expressions :)
![image](https://user-images.githubusercontent.com/30330327/120939200-2393dc00-c717-11eb-97d8-fc932e038e41.png)
![image](https://user-images.githubusercontent.com/30330327/120939292-b2a0f400-c717-11eb-98a9-d75288e2e3f3.png)
![image](https://user-images.githubusercontent.com/30330327/120939204-27276300-c717-11eb-8cb3-d080ba72fa7d.png)
![image](https://user-images.githubusercontent.com/30330327/120939306-c51b2d80-c717-11eb-9161-e6d666767aa7.png)

**Comment by mastersign** [comment]
Good point.

**Comment by kaifuzi** [comment]
So will you release a new version to support `left` and `right` function?

**Comment by mastersign** [comment]
I am working on version 0.6.0 with some changes to the way, the `EvaluationContext` is configured. But I can't make any promises, when I can release it.

So far, you can of course, register `left` and `right` yourself:

```csharp
context.AddFunction("left", (Func<string, int, string>)((value, count) => count >= value.Length ? value : value.Substr(0, count)));
context.AddFunction("right", (Func<string, int, string>)((value, count) => count >= value.Length ? value : value.Substr(value.Length - count)));
```

**Comment by kaifuzi** [comment]
Yes, for now it's enough for me by using `AddFunction`.
Thanks!
