### ISSUE TITLE
Concatenate string by +

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#21]
I knew we can use `&` to concatenate string, but because I put the expression in xaml file, I have to use `&amp;` instead of  `&`.
Is it possible to implement `+` to concatenate string?
e.g. : String1 + String2 => String1String2
　　 c_str(1) + c_str(2) =>12

**Comment by mastersign** [comment]
No, I am sorry. I would like to have theses operators distinctive.

**Comment by kaifuzi** [comment]
Do you have any idea that I can handle it by myself? Or is there any option for it in Mastersign.Expressions? Because I can't replace `+` by `&` simply.

**Comment by mastersign** [comment]
No you will have to write the `&amp;`.

For the relatively simple compiler to work, the add-operator for numeric values and the concatenation-operator for strings need to have different symbols.  I borrowed from the EXCEL formular language in using the `&` for the concatenation operator. In PHP the `.` is used for that same purpose, but because the `.` is already used for the member read functionality, I can not use that either. I do not plan to use more exotic characters for operators. And I do not plan to expose the operator symbols as configurable options, because there is more potential for misconfiguration. Which again, leads to a less simpler and customer friendly tool.

**Comment by kaifuzi** [comment]
Yes, I fully agree what you said. And I tested, Excel also doesn't support `+` to concatenate string.
The only problem is how to make `&` input simply in XML, but as you said, I have to use `&amp;`.
