### ISSUE TITLE
How to detect a variable is null or not?

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#22]
I add a variable, and its value is null:
`context.SetVariable("x", null);`
I try to use below expression, but all of them don't work:
`if(x=null,"0","1")`
`if(len(x)=0,"0","1")`
`if(c_str(x)="","0","1")`

**Comment by kaifuzi** [comment]
I try to use below customer function, but it doesn't work:
`context.AddFunction("IsNull", (Func<String, String, String>)((value1, value2) => value1 ?? value2));`

**Comment by mastersign** [comment]
I added the integrated function `isnull(x)` in version 0.7.0.

**Comment by mastersign** [comment]
The expressions `if(x=null,"0","1")` and `if(c_str(x)="","0","1")` are fixed in release 0.7.1.

**Comment by mastersign** [comment]
> I try to use below customer function, but it doesn't work: `context.AddFunction("IsNull", (Func<String, String, String>)((value1, value2) => value1 ?? value2));`

The definition of a string is more strict in Mastersign.Expressions then usual in .NET. Mastersign.Expression tries to prevent a `null` for values with the type of string, because null values are not well understood by non programmers. Null values are accepted for the object type however.

Therefore, the following custom function would work:  `context.AddFunction("DefaultString", (Func<Object, String, String>)((value1, value2) => value1 == null ? value2 : value1.ToString()));`
