### ISSUE TITLE
Sprache version is old in Demo project

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#6]
In Demo project, Sprache version is still the old one:
<package id="Sprache" version="1.10.0.28" targetFramework="net40-Client" />

**Comment by mastersign** [comment]
I can not reproduce this issue. The project `Mastersign.Expressions.Demo` has only the project reference to `Mastersign.Expressions`, and therefore, a transitive reference to the same Sprache version as `Mastersign.Expressions` it self.

Do I miss something?

**Comment by kaifuzi** [comment]
Maybe I misunderstanding, is the file packages.config not necessary anymore?
![image](https://user-images.githubusercontent.com/30330327/119529040-07d91f00-bd82-11eb-8e70-5821df1fa916.png)

**Comment by mastersign** [comment]
My bad. And yes the `packages.config` is no longer required. In an sdk-style project file, the additional `packages.config` file is no longer necessary, because the Nuget packages are referenced directly in the csproj file. In this case however, only the library project `Mastersign.Expressions` is referenced and no other package reference is required.

**Comment by kaifuzi** [comment]
I'm clear now. I saw you have deleted `packages.config`, so I close this issue. Thanks!
