### ISSUE TITLE
if(1=2, 10*2, 10^2) doesn't work

### ISSUE THREAD

**Issue by kaifuzi** [mastersign/Mastersign.Expressions#8]
When I execute "if(1=2, 10*2, 10^2)", I got error "The true part and the false part in the conditional must have the same type."

**Comment by mastersign** [comment]
Because `10^2` is implemented by `Math.Pow()` its result is `Double`. I have to admit, this is counter intuitive. This situation occurs, because I decided to be pedantic about the numeric data types in _Mastersign.Expressions_ in the attempt to increase performance.

As a workaround you can either use `if(1=2, c_double(10*2), 10^2)` or, if you are certain that the result of the power fits into `Int32` you can use `if(1=2, 10*2, c_int32(10^2))`.

I will try to implement automatic up-casting of numeric arguments in `if()` in an upcoming release.

**Comment by kaifuzi** [comment]
I understood what you are concerned about.
It will be greate to implement automatic up-casting of numeric arguments in if() in an upcoming release. This will make normal user's life be more easier.

**Comment by kaifuzi** [comment]
I saw this issue have been solved in version 0.5.1, very nice!
